#!/bin/sh

service mysql start

mysql -u root << EOF
	ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
	CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
	CREATE DATABASE IF NOT EXISTS $MYSQL_DB_NAME;
	GRANT ALL PRIVILEGES ON $MYSQL_DB_NAME.* TO '$MYSQL_USER'@'%';
	FLUSH PRIVILEGES;
	exit
EOF

# service mysql stop
